version: '3.8'

services:
  haiku-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haiku-telegram-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
